### PR TITLE
fix #32 - dlopen wrapper with RTLD_DEEPBIND

### LINKED ISSUE #32: Use RTLD_DEEPBIND ensure MPI implementation does not use symbols from Mukautuva
First, thanks for providing this library. This is exactly what I was looking for 😃.

I ran into an issue where OpenMPI called `MPI_Initialized` from Mukautuva. At least that's what I think what happens. I get a segmentation fault with the following backtrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff081798e in MPI_Initialized (flag=0x7fffffff8054) at libinit.c:820
#2  0x00007fffee86a065 in ?? () from /lib/x86_64-linux-gnu/libmpi_cxx.so.40
#3  0x00007fffee866217 in ?? () from /lib/x86_64-linux-gnu/libmpi_cxx.so.40
#4  0x00007ffff7fca71f in call_init (l=<optimized out>, argc=argc@entry=5, argv=argv@entry=0x7fffffffe3f8, env=env@entry=0x5555558b2800) at ./elf/dl-init.c:74
[…]
#17 ___dlopen (file=<optimized out>, mode=<optimized out>) at ./dlfcn/dlopen.c:81
#18 0x00007ffff0813201 in MUK_Alkaa (argc=0x0, argv=0x0, requested=2, provided=0x7fffffffdc64) at libinit.c:173
#19 0x00007ffff0817811 in MPI_Init_thread (argc=0x0, argv=0x0, requested=2, provided=0x7fffffffdc64) at libinit.c:768
```

Frame 19 is where I call `MPI_Init_thread`. In Frame 18, mukautuva calls `dlopen` with `ompi-wrap.so`. Frame 17-4 are internals from `dlopen`, but finally it calls into OpenMPIs libraries in Frame 3 and 2. In Frame 1, we want to call a null pointer, which leads to a segfault.

For me it looks, like `libmpi_cxx.so.40` wants to call `MPI_Initialized` from OpenMPIs `libmpi.so`, but it actually calls `MPI_Initialized` from mukautuva. There, the `MUK_Initialized` function pointer is still `null`.

I can reproduce this If I build mukautuva in a Rocky Linux 8.9, either with GCC 8.5 or 13.3.1 and then compile and run the client application on Ubuntu 24.04. It does not happen if I build mukautuva _and_ my client application on Ubuntu 24.04.

To fix this I added ` | RTLD_DEEPBIND` to the mode parameter of `dlopen` in `libinit.c:171`:

```cpp
    void * wrap_so_handle = dlopen(wrapname, RTLD_LAZY | RTLD_DEEPBIND);
```

I'm really no expert, but from how I understand the docs of `dlopen` this makes sense. What do you think about that?

### PR DESCRIPTION
**Pull request by thorink**
As discussed in https://github.com/jeffhammond/mukautuva/issues/32, this MR adds the `RTLD_DEEPBIND` flag to the `dlopen` call for the wrapper library.

### CODE REVIEW

File: libinit.c [hunk 1]
```diff
@@ -168,7 +168,11 @@ static int MUK_Alkaa(int * argc, char *** argv, int requested, int * provided)
     wrapname = pathname;
 #endif
 
-    void * wrap_so_handle = dlopen(wrapname, RTLD_LAZY | RTLD_DEEPBIND);
+    int flags = RTLD_LAZY;
```
Comment (dalcinl) [inline libinit.c]: For the sake of explicitness and completeness, maybe we should go for:
```suggestion
    int flags = RTLD_LOCAL | RTLD_LAZY;
```
Could you please test if things still work with this change?

Comment (thorink) [reply libinit.c]: Yes, this make sense for me. I tested it and it works. :+1:
